# Generated by Django 2.1.7 on 2019-02-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('about', models.CharField(max_length=10000)),
                ('signature', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
