# Generated by Django 2.1.7 on 2019-02-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=models.TextField(max_length=10000),
        ),
    ]
