# Generated by Django 2.1.7 on 2019-03-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190227_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='signature',
        ),
    ]
