# Generated by Django 2.1.7 on 2019-03-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190226_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime_close',
        ),
        migrations.RemoveField(
            model_name='order',
            name='datetime_open',
        ),
    ]
