# Generated by Django 2.1.7 on 2019-02-17 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('timestamp_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=512)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('timestamp_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=512)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete='Cascade', related_name='products', to='products.Category')),
            ],
        ),
    ]
