# Generated by Django 2.1.7 on 2019-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_life',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_mts',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_town',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_vel',
            field=models.CharField(max_length=13),
        ),
    ]
