# Generated by Django 2.1.7 on 2019-02-27 19:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('body', models.TextField(max_length=10000)),
                ('timestamp_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete='Cascade', related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
