# Generated by Django 2.1.7 on 2019-03-28 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_auto_20190328_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete='Cascade', related_name='review_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
