# Generated by Django 2.1.7 on 2019-03-28 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190328_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete='Cascade', related_name='review_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
